### ISSUE TITLE
add ctl schema command

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/click#119]
`click ctl schema --for=create|get|update|delete`

```yaml
kind: Namespace|Link|...
payload:
  ID%TYPE: string
  Some%TYPE: other
```
